CtrProyectoLuis/Controllers/ProductosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BEUcrtProyectoLuis;
using BEUcrtProyectoLuis.Queris;

namespace CtrProyectoLuis.Controllers
{
    public class ProductosController : Controller
    {
        private Entities db = new Entities();

        // GET: Productos
        public ActionResult Index()
        {
            var producto = db.Producto.Include(p => p.Categoria).Include(p => p.Promocion);
            return View(producto.ToList());
        }

        // GET: Productos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Producto producto = db.Producto.Find(id);
            if (producto == null)
            {
                return HttpNotFound();
            }
            return View(producto);
        }

        // GET: Productos/Create
        public ActionResult Create()
        {
            ViewBag.cat_id = new SelectList(db.Categoria, "cat_id", "cat_nom");
            ViewBag.prm_id = new SelectList(db.Promocion, "prm_id", "prm_nom");
            return View();
        }

        // POST: Productos/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "prd_id,cat_id,prm_id,prd_nom,prd_img,prd_tal,prd_crt,prd_cnt,prd_dateOfCreated,prd_precio")] Producto producto)
        {
            HttpPostedFileBase fileBase = Request.Files[0];
            string path = SubirImagen(fileBase);
            if (path != "")
            {
                producto.prd_img = path;
            }
            else
            {
                producto.prd_img = "default";
            }
            if (ModelState.IsValid)
            {
                db.Producto.Add(producto);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.cat_id = new SelectList(db.Categoria, "cat_id", "cat_nom", producto.cat_id);
            ViewBag.prm_id = new SelectList(db.Promocion, "prm_id", "prm_nom", producto.prm_id);
            return View(producto);
        }

        // GET: Productos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Producto producto = db.Producto.Find(id);
            if (producto == null)
            {
                return HttpNotFound();
            }
            ViewBag.cat_id = new SelectList(db.Categoria, "cat_id", "cat_nom", producto.cat_id);
            ViewBag.prm_id = new SelectList(db.Promocion, "prm_id", "prm_nom", producto.prm_id);
            return View(producto);
        }

        // POST: Productos/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "prd_id,cat_id,prm_id,prd_nom,prd_img,prd_tal,prd_crt,prd_cnt,prd_dateOfCreated,prd_precio")] Producto producto)
        {
            if (ModelState.IsValid)
            {
                db.Entry(producto).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.cat_id = new SelectList(db.Categoria, "cat_id", "cat_nom", producto.cat_id);
            ViewBag.prm_id = new SelectList(db.Promocion, "prm_id", "prm_nom", producto.prm_id);
            return View(producto);
        }

        // GET: Productos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Producto producto = db.Producto.Find(id);
            if (producto == null)
            {
                return HttpNotFound();
            }
            return View(producto);
        }

        // POST: Productos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Producto producto = db.Producto.Find(id);
            db.Producto.Remove(producto);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        private string SubirImagen(HttpPostedFileBase file)
        {
            string nombre = "";
            if (file != null && file.ContentLength > 0)
                try
                {
                    ArchivoBLL modelo = new ArchivoBLL();
                    nombre = DateTime.Now.ToString("yyyyMMddHHmmss") + file.FileName;
                    string path = Server.MapPath("~/Content/Imagenes/") + nombre;
                    modelo.SubirArchivo(path, file);
                    ViewBag.Message = modelo.confirmacion;
                }
                catch (Exception ex)
                {
                    ViewBag.Message = "ERROR:" + ex.Message.ToString();
                }
            return nombre;
        }
    }
}

CtrProyectoLuis/Views/Productos/Create.cshtml
@model BEUcrtProyectoLuis.Producto

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Productos", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Producto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.cat_id, "cat_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("cat_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.cat_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.prm_id, "prm_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("prm_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.prm_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.prd_nom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.prd_nom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.prd_nom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.prd_img, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="imageload" id="file" required />
                @*@Html.EditorFor(model => model.prd_img, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.prd_img, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.prd_tal, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.prd_tal, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.prd_tal, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.prd_crt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.prd_crt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.prd_crt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.prd_cnt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.prd_cnt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.prd_cnt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.prd_dateOfCreated, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.prd_dateOfCreated, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.prd_dateOfCreated, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.prd_precio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.prd_precio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.prd_precio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CtrProyectoLuis/Views/Productos/Delete.cshtml
@model BEUcrtProyectoLuis.Producto

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Producto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.prd_nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.prd_nom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.prd_img)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.prd_img)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.prd_tal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.prd_tal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.prd_crt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.prd_crt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.prd_cnt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.prd_cnt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.prd_dateOfCreated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.prd_dateOfCreated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.prd_precio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.prd_precio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Categoria.cat_nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Categoria.cat_nom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Promocion.prm_nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Promocion.prm_nom)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CtrProyectoLuis/Views/Productos/Details.cshtml
@model BEUcrtProyectoLuis.Producto

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Producto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.prd_nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.prd_nom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.prd_img)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.prd_img)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.prd_tal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.prd_tal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.prd_crt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.prd_crt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.prd_cnt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.prd_cnt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.prd_dateOfCreated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.prd_dateOfCreated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.prd_precio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.prd_precio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Categoria.cat_nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Categoria.cat_nom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Promocion.prm_nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Promocion.prm_nom)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.prd_id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CtrProyectoLuis/Views/Productos/Edit.cshtml
@model BEUcrtProyectoLuis.Producto

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Producto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.prd_id)

        <div class="form-group">
            @Html.LabelFor(model => model.cat_id, "cat_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("cat_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.cat_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.prm_id, "prm_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("prm_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.prm_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.prd_nom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.prd_nom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.prd_nom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.prd_img, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.prd_img, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.prd_img, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.prd_tal, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.prd_tal, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.prd_tal, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.prd_crt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.prd_crt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.prd_crt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.prd_cnt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.prd_cnt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.prd_cnt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.prd_dateOfCreated, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.prd_dateOfCreated, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.prd_dateOfCreated, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.prd_precio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.prd_precio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.prd_precio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CtrProyectoLuis/Views/Productos/Index.cshtml
@model IEnumerable<BEUcrtProyectoLuis.Producto>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.prd_nom)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.prd_img)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.prd_tal)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.prd_crt)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.prd_cnt)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.prd_dateOfCreated)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.prd_precio)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Categoria.cat_nom)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Promocion.prm_nom)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.prd_nom)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.prd_img)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.prd_tal)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.prd_crt)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.prd_cnt)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.prd_dateOfCreated)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.prd_precio)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Categoria.cat_nom)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Promocion.prm_nom)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.prd_id }) |
            @Html.ActionLink("Details", "Details", new { id=item.prd_id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.prd_id })
        </td>
    </tr>
}

</table>